-- Smart Library Book Issue & Return Management System
-- Core table definitions. Apply constraints.sql after this file.

CREATE TABLE roles (
	role_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	role_code VARCHAR(50) NOT NULL,
	role_name VARCHAR(100) NOT NULL,
	description VARCHAR(255) NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (role_id),
	UNIQUE KEY uk_roles_role_code (role_code),
	UNIQUE KEY uk_roles_role_name (role_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
	user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	role_id BIGINT UNSIGNED NOT NULL,
	library_card_no VARCHAR(30) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	username VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL,
	phone_number VARCHAR(20) NULL,
	password_hash VARCHAR(255) NOT NULL,
	status ENUM('ACTIVE', 'INACTIVE', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE',
	last_login_at DATETIME NULL,
	password_changed_at DATETIME NULL,
	email_verified_at DATETIME NULL,
	deleted_at DATETIME NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id),
	UNIQUE KEY uk_users_library_card_no (library_card_no),
	UNIQUE KEY uk_users_username (username),
	UNIQUE KEY uk_users_email (email),
	UNIQUE KEY uk_users_phone_number (phone_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE categories (
	category_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	category_code VARCHAR(50) NOT NULL,
	category_name VARCHAR(150) NOT NULL,
	description VARCHAR(255) NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	deleted_at DATETIME NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (category_id),
	UNIQUE KEY uk_categories_category_code (category_code),
	UNIQUE KEY uk_categories_category_name (category_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE authors (
	author_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	pen_name VARCHAR(150) NULL,
	biography TEXT NULL,
	email VARCHAR(150) NULL,
	website_url VARCHAR(255) NULL,
	nationality VARCHAR(100) NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	deleted_at DATETIME NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (author_id),
	UNIQUE KEY uk_authors_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE books (
	book_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	category_id BIGINT UNSIGNED NOT NULL,
	isbn VARCHAR(20) NOT NULL,
	call_number VARCHAR(50) NOT NULL,
	title VARCHAR(255) NOT NULL,
	subtitle VARCHAR(255) NULL,
	description TEXT NULL,
	publisher VARCHAR(150) NULL,
	publication_year YEAR NULL,
	edition VARCHAR(50) NULL,
	language VARCHAR(50) NOT NULL DEFAULT 'English',
	status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
	cover_image_url VARCHAR(255) NULL,
	deleted_at DATETIME NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (book_id),
	UNIQUE KEY uk_books_isbn (isbn),
	UNIQUE KEY uk_books_call_number (call_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE book_copies (
	copy_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	book_id BIGINT UNSIGNED NOT NULL,
	accession_number VARCHAR(50) NOT NULL,
	barcode VARCHAR(100) NOT NULL,
	shelf_location VARCHAR(100) NULL,
	copy_status ENUM('AVAILABLE', 'ISSUED', 'RESERVED', 'LOST', 'DAMAGED', 'MAINTENANCE', 'ARCHIVED') NOT NULL DEFAULT 'AVAILABLE',
	acquired_on DATE NULL,
	notes VARCHAR(255) NULL,
	deleted_at DATETIME NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (copy_id),
	UNIQUE KEY uk_book_copies_accession_number (accession_number),
	UNIQUE KEY uk_book_copies_barcode (barcode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE book_authors (
	book_id BIGINT UNSIGNED NOT NULL,
	author_id BIGINT UNSIGNED NOT NULL,
	contribution_role VARCHAR(50) NOT NULL DEFAULT 'AUTHOR',
	is_primary_author TINYINT(1) NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (book_id, author_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE issued_books (
	issue_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	copy_id BIGINT UNSIGNED NOT NULL,
	user_id BIGINT UNSIGNED NOT NULL,
	issued_by_user_id BIGINT UNSIGNED NULL,
	returned_by_user_id BIGINT UNSIGNED NULL,
	issue_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	due_date DATETIME NOT NULL,
	return_date DATETIME NULL,
	renewal_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	issue_status ENUM('ISSUED', 'RETURNED', 'OVERDUE', 'LOST', 'CANCELLED') NOT NULL DEFAULT 'ISSUED',
	remarks VARCHAR(255) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (issue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fines (
	fine_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	issue_id BIGINT UNSIGNED NOT NULL,
	fine_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	fine_rate_per_day DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	overdue_days INT UNSIGNED NOT NULL DEFAULT 0,
	payment_status ENUM('PENDING', 'PARTIALLY_PAID', 'PAID', 'WAIVED') NOT NULL DEFAULT 'PENDING',
	assessed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	paid_at DATETIME NULL,
	waived_at DATETIME NULL,
	remarks VARCHAR(255) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (fine_id),
	UNIQUE KEY uk_fines_issue_id (issue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE transactions (
	transaction_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	issue_id BIGINT UNSIGNED NOT NULL,
	fine_id BIGINT UNSIGNED NULL,
	user_id BIGINT UNSIGNED NOT NULL,
	processed_by_user_id BIGINT UNSIGNED NULL,
	transaction_type ENUM('ISSUE', 'RETURN', 'FINE_PAYMENT', 'FINE_WAIVER') NOT NULL,
	transaction_status ENUM('SUCCESS', 'PENDING', 'FAILED', 'REVERSED') NOT NULL DEFAULT 'SUCCESS',
	payment_method ENUM('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'ONLINE', 'NOT_APPLICABLE') NOT NULL DEFAULT 'NOT_APPLICABLE',
	transaction_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	reference_no VARCHAR(100) NULL,
	remarks VARCHAR(255) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (transaction_id),
	UNIQUE KEY uk_transactions_reference_no (reference_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
